<?php

use App\Http\Controllers\BookingPaymentController;
use App\Http\Controllers\BorrowedFundController;
use App\Http\Controllers\FundRepaymentController;
use App\Http\Controllers\IncomeCategoryController;
use App\Http\Controllers\IncomeController;
use App\Http\Controllers\LenderController;
use App\Http\Controllers\TransactionController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\BookingController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\ExpenseCategoryController;
use App\Http\Controllers\ExpenseController;
use App\Http\Controllers\MonthlySalaryController;
use App\Http\Controllers\ReportController;
use App\Http\Controllers\SalaryPaymentController;
use App\Http\Controllers\WorkerController;
use App\Models\Worker;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
*/

// Public routes generated by Breeze (Login, Register, etc.)
// No changes needed here. The require line handles them.
require __DIR__ . '/auth.php';


// All application routes should be accessible only to logged-in users.
// We will wrap them in the 'auth' middleware group.
Route::middleware(['auth'])->group(function () {

    // Main redirect to dashboard
    Route::get('/', function () {
        return redirect()->route('dashboard');
    });

    // Dashboard Route
    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');

    Route::get('/bookings/{booking}/receipt-pdf', [BookingController::class, 'downloadReceiptPDF'])->name('bookings.receipt.pdf');
    // Booking Routes
    Route::resource('bookings', BookingController::class);

    // Expense Category Routes
    Route::resource('expense-categories', ExpenseCategoryController::class)->except(['show']);

    // Expense Routes
    Route::resource('expenses', ExpenseController::class)->except(['show']);

    // Reports Route
    Route::get('/reports/profit-loss', [ReportController::class, 'profitAndLoss'])->name('reports.profit_loss');
    Route::get('/reports/profit-loss/pdf', [ReportController::class, 'exportProfitAndLossPDF'])->name('reports.profit_loss.pdf');
// Worker Management
    Route::resource('workers', WorkerController::class);

    // Salary Management & Payment Routes
    Route::prefix('salaries')->name('salaries.')->group(function () {
        Route::get('/', [MonthlySalaryController::class, 'index'])->name('index');
        Route::post('/generate', [MonthlySalaryController::class, 'generate'])->name('generate');

        // Routes for a specific Monthly Salary record
        Route::get('/{monthlySalary}', [MonthlySalaryController::class, 'show'])->name('show');
        Route::get('/{monthlySalary}/edit', [MonthlySalaryController::class, 'edit'])->name('edit');
        Route::put('/{monthlySalary}', [MonthlySalaryController::class, 'update'])->name('update');

        // Route for storing a new payment against a monthly salary
        Route::post('/{monthlySalary}/payments', [SalaryPaymentController::class, 'store'])->name('payments.store');
    });

    // Routes for editing/deleting a specific Salary Payment record
    Route::prefix('salary-payments')->name('salary-payments.')->group(function () {
        Route::get('/{salaryPayment}/edit', [SalaryPaymentController::class, 'edit'])->name('edit');
        Route::put('/{salaryPayment}', [SalaryPaymentController::class, 'update'])->name('update');
        Route::delete('/{salaryPayment}', [SalaryPaymentController::class, 'destroy'])->name('destroy');
    });

    Route::resource('lenders', LenderController::class)->except(['show']);
    Route::resource('borrowed-funds', BorrowedFundController::class);
    Route::post('borrowed-funds/{borrowedFund}/repayments', [FundRepaymentController::class, 'store'])->name('borrowed-funds.repayments.store');
    Route::delete('fund-repayments/{fundRepayment}', [FundRepaymentController::class, 'destroy'])->name('fund-repayments.destroy');

    Route::resource('income-categories', IncomeCategoryController::class)->except(['show']);
    Route::resource('incomes', IncomeController::class)->except(['show']);
    Route::post('bookings/{booking}/payments', [BookingPaymentController::class, 'store'])->name('bookings.payments.store');

// Delete a specific payment record
    Route::delete('booking-payments/{bookingPayment}', [BookingPaymentController::class, 'destroy'])->name('booking-payments.destroy');

    Route::get('/transactions', [TransactionController::class, 'index'])->name('transactions.index');
    Route::get('/transactions/pdf', [TransactionController::class, 'exportPDF'])->name('transactions.pdf');
});
